language: python
python: 3.6

sudo: false

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install --upgrade pip setuptools
  - pip install --upgrade -r test_requirements.txt
  - pip install -e .

before_script:
  - flake8 --max-complexity 10 src tests

script:
  - coverage run -m py.test {posargs} {toxinidir}/test/
  - coverage report
